name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9
    
    - name: Run pnpm install
      run: pnpm install

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Run ESLint tests
      run: pnpm run test-lint
      env:
        CI: true
